### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by bemau** [salesforce/Providence#11]
Folks,
I got this error trying to run the providence.py

> AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

I guess because the requests in the requirements.txt is the 2.3.0
Using the 2.6.0 as explained in this post fixed my issue
https://stackoverflow.com/a/29081240
is worth to upgrade the requests from 2.3.0 to 2.6.0?
Any input is more than welcome

> $ python providence.py
> Traceback (most recent call last):
>   File "providence.py", line 29, in <module>
>     from Empire.creds import CredentialManager
>   File "/home/mauri/Documents/git/Providence/Empire/creds/__init__.py", line 27, in <module>
>     from creds.credentials import Credentials 
>   File "/home/mauri/Documents/git/Providence/Empire/creds/__init__.py", line 27, in <module>
>     from creds.credentials import Credentials 
>   File "/home/mauri/Documents/git/Providence/Empire/creds/credentials.py", line 24, in <module>
>     import requests
>   File "/home/mauri/Documents/git/Providence/venv/local/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
>     from .packages.urllib3.contrib import pyopenssl
>   File "/home/mauri/Documents/git/Providence/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 70, in <module>
>     ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
> AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
> 

`$ uname -a`
`Linux mauri-B202 4.13.0-41-generic #46-Ubuntu SMP Wed May 2 13:38:12 UTC 2018 i686 i686 i686 GNU/Linux`

**Comment by ghost** [comment]
Short answer - yes.  For most purposes you shouldn't want to use SSLv3 (or even TLS 1.0) as they're deprecated protocols with known security flaws.  I can't 100% guarantee it'll break anything else, but it's a pretty low likelihood as requests is pretty self-contained.

**Comment by bemau** [comment]
@bweisshaarsf thanks Barrett!
